channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - graphviz
  - numpy
  - seaborn
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - mkl-service
  - dask
  - dask-kubernetes
  - distributed
  - tornado=5.1.1
  - pip:
    - arviz
    - git+https://github.com/davidbrochart/pymc3@dask_smc
    - dask_labextension==0.3.3
