channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.0.4
  - graphviz
  - numpy
  - seaborn
  - dask=1.1.4
  - distributed=1.26.0
  - dask-kubernetes=0.7.0
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - pip:
    - arviz
    - git+https://github.com/davidbrochart/pymc3@dask_smc
