channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - graphviz
  - numpy
  - seaborn
  - distributed
  - dask-kubernetes
  - nbserverproxy
  - jupyter
  - jupyterlab
  - mkl-service
  - pip:
    - arviz
    - git+https://github.com/davidbrochart/pymc3@dask_smc
    - git+https://github.com/dask/dask
